<header>
	<h2><?php echo $this->translate('Delete entry'); ?></h2>
</header>

<section>

	<form name="deleteGuestbookEntryForm" action="" method="post">
		<dl>
			<dt width="200"><label class="label"><?php echo $this->translate('Name'); ?></label></dt>
			<dd width="*" class="text"><?php echo $this->entry['guestbook_name']; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Email'); ?></label></dt>
			<dd class="text"><?php echo $this->entry['guestbook_email']; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Date'); ?></label></dt>
			<dd class="text"><?php echo $this->date()->format($this->entry['guestbook_entry_date'], 'dd-MM-YYYY'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Status'); ?></label></dt>
			<dd class="text"><?php echo $this->translate((($this->entry['guestbook_entry_verified'] == 'y') ? 'Active' : 'Inactive')); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Message'); ?></label></dt>
			<dd class="text"><?php echo nl2br($this->entry['guestbook_message']); ?></dd>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
			<dd></dd>
		</dl>
		<dl>
			<dd><?php echo $this->translate('Are you sure you want to delete this guestbook entry?'); ?></dd>
		</dl>
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Yes'); ?>" style="margin-right: 15px;" />
				<a href="/admin/guestbook/" title="<?php echo $this->translate('Or, go back to overview'); ?>"><?php echo $this->translate('Or, go back to overview'); ?></a>
			</dd>
		</dl>
	</form>

</section>
