<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Iamsterdam.com</title>
<style type="text/css">
*{
	margin:0;
	padding:0;
	border:0;	
}
body {
	background:#fff;
	font-family:arial;
}
p{
	margin-bottom:12px;
}

</style>
</head>

<body>
	<h1><?php echo $this->title; ?></h1>
	<p><?php echo $this->content; ?></p>
</body>
</html>