<div id="nextpage" class="zapp blog">
    <div class="col left">
        <div class="inner">
            <h2><?php echo html_entity_decode($this->item['title']); ?></h2>
            <span class="blog-date"><?php echo $this->date()->format($this->item['created'], 'dd MMM yyyy'); ?></span>
            <?php echo html_entity_decode($this->item['content']); ?>
        </div>
    </div>
    <div class="col right">

        <div class="item news">
            <div class="media zapp">
                <div class="media__img">
                    <img class="profiles__avatar" src="<?php echo $this->blogger['photo']; ?>" title="<?php echo $this->blogger['name']; ?>" alt="<?php echo $this->blogger['name']; ?>">
                </div>
                <div class="media__body media__body--loggedin">
                    <ul>
                        <li><?php echo $this->blogger['name']; ?></li>
                        <li><?php echo $this->blogger['quote']; ?></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="item news bg_kz_lightgrey">
            <h2>Laatste blogs</h2>
            <?php
                if(! empty($this->recent) && is_array($this->recent)) {
                    echo '<ul>';
                    foreach($this->recent as $arrRecent) {
                        echo '<li>
                                <span class="date newstag">'.$this->date()->format($arrRecent['created'], 'dd MMM yyyy').'</span>
                                <a href="/blog/'.$this->blogger['slug'].'/'.$arrRecent['slug'].'/" title="">'.$arrRecent['title'].'</a>
                              </li>';
                    }
                    echo '</ul>';
                } else {
                    echo 'Er zijn nog geen blog berichten van '.$this->blogger['name'].'.';
                }
            ?>
        </div>
    </div>
</div>
