<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="DC.language" content="en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="Author" content="Webathletes.nl">
    <?php echo $this->headMeta(); ?>
    <title><?php echo $this->seo_title; ?></title>
    <meta name="Description" content="<?php echo $this->seo_description; ?>">
    <meta name="Keywords" content="<?php echo $this->seo_keywords; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="/assets/default/image/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/default/image/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/default/image/favicon/favicon-16x16.png">
    <link rel="manifest" href="/assets/default/image/favicon/manifest.json">
    <link rel="mask-icon" href="/assets/default/image/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <link href="/assets/default/css/app.min.css" rel="stylesheet" type="text/css">
    <script src="/assets/default/script/app.sync-min.js"></script>
</head>
<body>
<div id="full-container">
    <?php echo $this->profiles(); ?>
    <div class="menu-container" style="display: none;">
        <?php echo $this->navigator(1); ?>
    </div>
    <div class="content-container">
        <header class="zapp">
            <div class="portrait">
                <div class="menu_button_container">
                    <span class="menu_button">menu
                        <span class="downarrow"><span aria-hidden="true">&#xe000;</span></span>
                    </span>
                </div>
                <a href="/"><img class="logo" src="/assets/default/image/logo_kzthermo4u_portrait.png"
                                 alt="Logo kz/thermo4u"></a>
            </div>
            <ul class="col right">
                <li>
                    <a class="contact<?php echo((isset($this->activeRouteContact) && $this->activeRouteContact === true) ? ' hover' : ''); ?>"
                       href="/route-contact">contact en route</a></li>
                <li class="sm">
                    <span class="title">volg ons:</span>
                    <a class="twitter" href="https://twitter.com/KZ_Thermo4U" target="_blank"><span>twitter</span></a>
                    <a class="facebook" href="http://www.facebook.com/kvkoogzaandijk"
                       target="_blank"><span>facebook</span></a>
                </li>
                <li class="search">
                    <label>Zoek:</label>
                    <input type="text" name="search" id="search" value="" onkeyup="searchSuggestions(this.value);">
                    <ul id="suggestions"></ul>
                </li>
            </ul>
            <?php echo $this->profiles('button'); ?>
        </header>
        <div class="menu-container-oncanvas">
            <?php echo $this->navigator(1); ?>
        </div>
        <div id="wrapper_main" class="zapp">
            <div class="col main left">
                <div class="wrapper_inner">

                    <!--<a class="header--eindsprong" href="https://www.eindsprong.nl" title="Website Eindsprong" target="_blank">
                        <img src="/assets/default/image/header_website.gif" alt="Banner eindsprong" title="Klik hier om naar de speciale website te gaan" />
                    </a>-->

                    <?php echo $this->breadcrumb(); ?>

                    <?php echo $this->carousel(); ?>

                    <?php echo $this->layout()->content; ?>

                    <?php echo $this->news(); ?>

                    <?php echo $this->widgets(); ?>

                    <?php echo $this->navigator(2); ?>

                </div>
            </div>
            <!--<div class="col main right">
                <iframe allowtransparency="true" frameborder="0" width="144" scrolling="no" src="https://www.sponsorportaal.nl/shared/banner/?id=4e82de436577a"></iframe>
                <iframe allowtransparency="true" frameborder="0" width="144" scrolling="no" src="https://www.sponsorportaal.nl/shared/banner/?id=4e82de475ba80"></iframe>
                <iframe allowtransparency="true" frameborder="0" width="144" scrolling="no" src="https://www.sponsorportaal.nl/shared/banner/?id=4e82de4c91af2"></iframe>
                <iframe allowtransparency="true" frameborder="0" width="144" scrolling="no" src="https://www.sponsorportaal.nl/shared/banner/?id=4e82deb699c93"></iframe>
            </div>-->
        </div>
    </div>
</div>
<div id="fb-root"></div>
<?php echo $this->googleanalytics; ?>
<script src="/assets/default/script/app.async-min.js"></script>
</body>
</html>