<p><?php echo $this->translate('Welcome to the KZ/Thermo4U admin panel.'); ?></p>
<p><?php echo $this->translate('Please fill in the e-mail adres which you are registered with.'); ?></p>
		
<form method="post" name="loginForm" action="">
	<fieldset>
		<dl>
			<dt class="forgot">
				<label for="name"><?php echo $this->translate('Email'); ?></label>
			</dt>
			<dd class="medium">
				<input name="email" type="text" id="email">
			</dd>
		</dl>
	</fieldset>
	<a href="/admin/login/">&laquo; <?php echo $this->translate('back'); ?></a>
	<input type="submit" class="button right" value="Resend Password" />
</form>