<script type="text/javascript">

	jQuery(document).ready(function(){

		jQuery('a.button').click(function(){

			var rel 		= jQuery(this).attr('rel');
			var buttonClass = jQuery(this).attr('class');

			jQuery('#'+rel).attr('checked', ((jQuery('#'+rel).attr('checked') == 'checked') ? false : true));
			jQuery(this).removeClass(((jQuery('#'+rel).attr('checked') == 'checked') ? 'red' : 'green'));
			jQuery(this).addClass(((jQuery('#'+rel).attr('checked') == 'checked') ? 'green' : 'red'));

		});
		
		var type = jQuery('#content_type_id').val();

		if(type == 0) {
			jQuery('.layoutPreview').css('display', 'none');
		} else {
			jQuery('.layoutPreview').css('display', 'block');
			jQuery('.layoutPreview').attr('href', '/assets/admin/image/layout/type' + type + '.jpg');
			jQuery('.layoutPreview img').attr('src', '/assets/admin/image/layout/thumb_type' + type + '.jpg');
		}
		
		jQuery('.content_type').hide();
		jQuery('#content_'+type).toggle();
		jQuery('#activeContentType').val(type);

		jQuery('#content_type_id').change(function(){

			var type = jQuery(this).val();

			if(type == 0) {
				jQuery('.layoutPreview').css('display', 'none');
			} else {
				jQuery('.layoutPreview').css('display', 'block');
				jQuery('.layoutPreview').attr('href', '/assets/admin/image/layout/type' + type + '.jpg');
				jQuery('.layoutPreview img').attr('src', '/assets/admin/image/layout/thumb_type' + type + '.jpg');
			}
			
			jQuery('.content_type').hide();
			jQuery('#content_'+type).toggle();
			jQuery('#activeContentType').val(type);

		});

		jQuery("a.layoutPreview").fancybox({
			width: '50%',
			height: '100%',
			showNavArrows: false
		});

	});

</script>
<header>
	<h2><?php echo $this->translate('Edit content for page').' '.$this->name; ?></h2>
</header>

<section>

	<form name="editPageContentForm" method="post" action="">
		<dl>
			<dt width="200"><label class="label" for="name"><?php echo $this->translate('Name'); ?></label></dt>
			<dd width="*"><input type="text" class="small" id="name" name="name" value="<?php echo $this->name; ?>" /></dd>
		</dl>
		<dl>
			<dt><label class="label" for="content_type_id"><?php echo $this->translate('Layout'); ?></label></dt>
			<dd>
			
				<?php
					if(isset($this->contentTypes) && is_array(($this->contentTypes))) {
							
						echo '<select class="small" name="content_type_id" id="content_type_id"><option value="0">'.$this->translate('Choose').'</option>';
						
						foreach($this->contentTypes as $intContentTypeKey => $arrContentType) {
								
							if($arrContentType['status'] == 1) {
									
								$strSelected	= (($arrContentType['content_type_id'] == $this->content_type_id) ? ' selected="selected"' : '');
								
								echo '<option value="'.$arrContentType['content_type_id'].'" '.$strSelected.'>'.$this->translate($arrContentType['name']).'</option>';
									
							}
							
						}

						echo '</select>';
						
					}
				?>
			</dd>
		</dl>
		<dl>
			<dt><label class="label" for="status"><?php echo $this->translate('Status'); ?></label></dt>
			<dd>
				<select class="small" name="status">
					<option value="1"<?php echo (($this->status == 1) ? ' selected="selected"' : ''); ?>>Active</option>
					<option value="0"<?php echo (($this->status == 1) ? '' : 'selected="selected"'); ?>>Inactive</option>
				</select>
			</dd>
		</dl>
		
		<dl>
			<dt>&nbsp;</dt>
			<dd><a class="layoutPreview" style="display: none;" href="" title=""><img src="" alt="" title=""></a></dd>
		</dl>
		
		<div id="content_1" class="content_type">
			
			<dl>
				<dt>&nbsp;</dt>
				<dd><label class="label"><?php echo $this->translate('Title and text'); ?></label></dd>	
			</dl>
			<dl>
				<dt width="200"><label class="label" for="content_1_title"><?php echo $this->translate('Title'); ?></label></dt>
				<dd width="*"><input type="text" class="small" id="content_1_title" name="content_1_title" value="<?php echo stripslashes($this->content_1_title); ?>" /></dd>
			</dl>
			<dl>
				<dt><label class="label" for="content_1_text"><?php echo $this->translate('Text'); ?></label></dt>
				<dd><textarea name="content_1_text" rows="5" cols="40" class="tinymce" style="width: 80%; height: 450px"><?php echo stripslashes($this->content_1_text); ?></textarea></dd>
			</dl>

		</div>
		
		<div id="content_2" class="content_type">
			
			<dl>
				<dt>&nbsp;</dt>
				<dd><label class="label"><?php echo $this->translate('Title, image and text'); ?></label></dd>	
			</dl>
			<dl>
				<dt width="200"><label class="label" for="content_2_title"><?php echo $this->translate('Title'); ?></label></dt>
				<dd width="*"><input type="text" class="small" id="content_2_title" name="content_2_title" value="<?php echo stripslashes($this->content_2_title); ?>" /></dd>
			</dl>
			<dl>
				<dt><label class="label" for="content_2_image"><?php echo $this->translate('Image'); ?></label></dt>
				<dd><input type="text" class="small" id="content_2_image" name="content_2_image" value="<?php echo $this->content_2_image; ?>" /> <a class="button" href="javascript:mcImageManager.open('editPageContentForm','content_2_image');"><?php echo $this->translate('Select image'); ?></a></dd>
			</dl>
			<dl>
				<dt><label class="label" for="content_2_text"><?php echo $this->translate('Text'); ?></label></dt>
				<dd><textarea name="content_2_text" rows="5" cols="40" class="tinymce" style="width: 80%; height: 450px"><?php echo stripslashes($this->content_2_text); ?></textarea></dd>
			</dl>
			

		</div>		
		
		<div id="content_3" class="content_type">

			<dl>
				<dt>&nbsp;</dt>
				<dd><label class="label"><?php echo $this->translate('Video'); ?></label></dd>	
			</dl>
			
			<dl>
				<dt width="200"><label class="label" for="content_3_video"><?php echo $this->translate('Video'); ?></label></dt>
				<dd width="*"><input type="text" class="small" id="content_3_video" name="content_3_video" value="<?php echo $this->content_3_video; ?>" /> </dd>
			</dl>
			
		</div>
		
		<div id="content_13" class="content_type">
	
			<dl>
				<dt>&nbsp;</dt>
				<dd><label><?php echo $this->translate('Teams'); ?></label></dd>	
			</dl>
			
			<dl>
				<dt width="200"><label class="label"><?php echo $this->translate('Teams'); ?></label></dt>
				<dd width="*">
					<div id="tagsContainer">
					<?php
						if(isset($this->team_categories) && is_array(($this->team_categories))) {
							foreach($this->team_categories as $arrTeamCategory) {

								$strStatus 			= ((isset($this->content_13_teams) && is_array($this->content_13_teams) && in_array($arrTeamCategory['category'], $this->content_13_teams)) ? ' checked="checked"' : '');
								$strColor 			= ((isset($this->content_13_teams) && is_array($this->content_13_teams) && in_array($arrTeamCategory['category'], $this->content_13_teams)) ? 'green' : 'red');
								
								echo '	<a class="button '.$strColor.' small" rel="team-'.$arrTeamCategory['category'].'">'.$arrTeamCategory['category'].'</a>
									  	<input type="checkbox" name="team-'.$arrTeamCategory['category'].'" id="team-'.$arrTeamCategory['category'].'" value="'.$arrTeamCategory['category'].'" style="display: none;" '.$strStatus.' />';
							}
						}
					?>
				</div>				
				</dd>
			</dl>

		</div>						

		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Save page content'); ?>" />
				<a href="/admin/pages/content/id/<?php echo $this->page_content['page_id']; ?>" title="<?php echo $this->translate('Or, go back to overview'); ?>"><?php echo $this->translate('Or, go back to overview'); ?></a>
			</dd>
		</dl>
		
		<input type="hidden" id="activeContentType" name="activeContentType" value="">
		
	</form>

</section>
<script language="JavaScript">

<?php if (isset($this->editorInit)) print $this->editorInit; ?>

</script>