<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('button.colorPicker').ColorPicker({
			onChange: function (hsb, hex, rgb) {
				jQuery('button.colorPicker').css('backgroundColor', '#'+hex);
				jQuery('#color').val('#' + hex);
			}
		});
		<?php if(isset($this->color) && ! empty($this->color)) : ?>

			jQuery('button.colorPicker').css('backgroundColor', '<?php echo $this->color; ?>');
		
		<?php endif; ?>
	});
</script>
<header>
	<h2><?php echo $this->translate('Edit category'); ?></h2>
</header>

<section>

		<form name="editCategoryForm" method="post" action="">
		
			<dl>
				<dt width="200"><label class="label" for="name"><?php echo $this->translate('Name'); ?></label></dt>
				<dd width="*"><input type="text" class="small" id="name" name="name" value="<?php echo $this->name; ?>" /></dd>
			</dl>
			<dl>
				<dt><label class="label"><?php echo $this->translate('Color'); ?></label></dt>
				<dd>
					<button class="colorPicker"></button>
					<input type="hidden" name="color" id="color" value="<?php echo $this->color;?>">
				</dd>
			</dl>
			<dl>
				<dt><label class="label" for="status"><?php echo $this->translate('Status'); ?></label></dt>
				<dd>
					<select class="small" name="status">
						<option value="1"<?php echo (($this->status == 1) ? ' selected="selected"' : ''); ?>>Active</option>
						<option value="0"<?php echo (($this->status == 1) ? '' : 'selected="selected"'); ?>>Inactive</option>
					</select>
				</dd>
			</dl>
			<dl>
				<dt height="15" colspan="2"></dt>
			</dl>
			<dl>
				<dt>&nbsp;</dt>
				<dd><input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Update category'); ?>" /></dd>
			</dl>
		
		</form>
	
</section>