<header>
	<h2><?php echo $this->translate('Delete news category'); ?></h2>
</header>
<section>
	<form name="deleteCategoryForm" method="post" action="">
	
		<dl>
			<dt width="200"><label class="label"><?php echo $this->translate('Title'); ?></label></dt>
			<dd width="*" class="text"><?php echo $this->defaults['title']; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Link'); ?></label></dt>
			<dd class="text">
				<?php 
					if($this->defaults['foreign_table'] == 'other') {
						echo $this->defaults['link'];
					} else {
						echo $this->defaults['foreign_table'].' '.$this->defaults['foreign_key'];
					}
				?>
			</dd>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Background color'); ?></label></dt>
			<dd class="text"><?php echo ucfirst(str_replace('_kz_','',$this->defaults['color_background'])); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Text color'); ?></label></dt>
			<dd class="text"><?php echo ucfirst(str_replace('_kz_','',$this->defaults['color_text'])); ?></dd>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Status'); ?></label></dt>
			<dd class="text"><?php echo $this->translate((($this->defaults['status'] == 1) ? 'Active' : 'Inactive')); ?></dd>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
			<dd><?php echo $this->translate('Are you sure you want to delete this news category?')?></dd>
		</dl>
		<dl>
			<dt height="15" colspan="2">&nbsp;</dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Yes'); ?>" />
				<?php echo '<a href="/admin/settings/newscategories/#tab0/">'.$this->translate('Or go back to overview'); ?></a>
			</dd>
		</dl>
	
	</form>
</section>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#foreign_table').change(function(){
			jQuery('#foreign_key_page').css('display','none');
			jQuery('#foreign_key_news').css('display','none');
			jQuery('#foreign_key_agenda').css('display','none');
			jQuery('#foreign_key_other').css('display','none');

			var foreignTable = jQuery(this).val();
			jQuery('#foreign_key_' + foreignTable).css('display','block');
		});
	});
</script>