<?php
    $objModelBlog = new KZ_Models_Blog();
    $arrBloggers = $objModelBlog->getBloggers(2);

    if(! empty($arrBloggers) && is_array($arrBloggers)) {
        echo '<div class="table--profiles table--profiles__widget">
                <ol class="profiles zapp">';
        foreach($arrBloggers as $arrBlogger) {
            echo '  <li class="profiles__profile">
                        <div class="media zapp">
                            <div class="media__img">
                                <a href="/blog/'.$arrBlogger['slug'].'/">
                                    <img class="profiles__avatar" src="'.$arrBlogger['photo'].'">
                                </a>
                            </div>
                            <div class="media__body media__body--profiles">
                                <a href="/blog/'.$arrBlogger['slug'].'/">'.$arrBlogger['name'].'</a><br />
                                bericht 1<br />
                                bericht 2
                            </div>
                        </div>
                    </li>';
        }
        echo '  </ol>
              </div>';
    } else {
        echo 'Er zijn nog geen bloggers toegevoegd';
    }