<header>
	<h2><?php echo $this->translate('Delete news'); ?></h2>
</header>

<section>

	<form name="deleteNewsForm" method="post" action="">

		<dl>
			<dt width="200"><label class="label"><?php echo $this->translate('Type'); ?></label></dt>
			<dd width="*" class="text"><?php echo ((isset($this->newsTypes[$this->news_type_id]['name']) && ! empty($this->newsTypes[$this->news_type_id]['name'])) ? $this->newsTypes[$this->news_type_id]['name'] : '-'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Category'); ?></label></dt>
			<dd class="text"><?php echo ((isset($this->categories[$this->category_id]['name']) && ! empty($this->categories[$this->category_id]['name'])) ? $this->categories[$this->category_id]['name'] : '-'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label" for="tags"><?php echo $this->translate('Tags'); ?></label></dt>
			<dd class="text">
				<?php
					$arrActiveTagNames = array();
					if(isset($this->active_tags) && is_array(($this->active_tags))) {
						
						foreach($this->active_tags as $intTagKey => $intTagID) {
							
							$arrActiveTagNames[] = $this->tags[$intTagID]['name'];
						}
						echo implode(', ', $arrActiveTagNames);
					} else {
						echo '-';
					}
				?>
			
			</dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Name'); ?></label></dt>
			<dd class="text"><?php echo stripslashes($this->name); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Date'); ?></label></dt>
			<dd class="text"><?php echo $this->date; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Time'); ?></label></dt>
			<dd class="text"><?php echo (($this->time <= 9) ? '0'.$this->time : $this->time).':00'; ?></dd>
		</dl>
        <dl>
            <dt><label class="label"><?php echo $this->translate('Activate at'); ?></label></dt>
            <dd class="text"><?php echo ((is_null($this->activate_at)) ? 'No activation date and time' : $this->activate_at); ?></dd>
        </dl>
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('SEO title'); ?></label></dt>
			<dd class="text"><?php echo ((isset($this->seo_title) && ! empty($this->seo_title)) ? $this->seo_title : '-'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('SEO description'); ?></label></dt>
			<dd class="text"><?php echo ((isset($this->seo_description) && ! empty($this->seo_description)) ? $this->seo_description : '-'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('SEO keywords'); ?></label></dt>
			<dd class="text"><?php echo ((isset($this->seo_keywords) && ! empty($this->seo_keywords)) ? $this->seo_keywords : '-'); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Status'); ?></label></dt>
			<dd class="text"><?php echo $this->translate((($this->status == 1) ? 'Active' : 'Inactive')); ?></dd>
		</dl>
		
		<?php if(isset($this->newsContent) && is_array($this->newsContent) && count($this->newsContent) > 0) : ?>
			
			<dl>
				<dt height="15" colspan="2"></dt>
			</dl>
			<dl>
				<dt>&nbsp;</dt>
				<dd class="text">
					<div class="notification attention">
						<p>
							<strong><?php echo $this->translate('Attention'); ?></strong>
							<?php echo $this->translate('Attached page content will also be deleted'); ?>
						</p>
					</div>
					
				</dd>
			</dl>
			
		
		<?php endif; ?>
		
		
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd class="text">&raquo; <?php echo $this->translate('Are you sure you want to delete this news'); ?>?</dd>
		</dl>
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Yes'); ?>" style="margin-right: 15px;" />
				<a href="/admin/news/index/" title="<?php echo $this->translate('No, go back to overview'); ?>"><?php echo $this->translate('No, go back to overview'); ?></a>
			</dd>
		</dl>
	
	</form>

</section>