<header>
	<h2><?php echo $this->translate('Show log'); ?></h2>
</header>

<section>

	<table>
		<tr>
			<td width="25%"><label><?php echo $this->translate('ID'); ?></label></td>
			<td width="75%"><?php echo $this->id; ?></td>
		</tr>
		<tr>
			<td><label><?php echo $this->translate('Date'); ?></label></td>
			<td><?php echo $this->date()->format($this->time, 'dd-MM-YYYY HH:mm:ss'); ?>
			</td>
		</tr>
		<tr>
			<td><label><?php echo $this->translate('IP'); ?></label></td>
			<td><?php echo $this->ip; ?></td>
		</tr>
		<tr>
			<td><label><?php echo $this->translate('Type'); ?></label></td>
			<td><span class="tag <?php echo (($this->type == 'error') ? 'red' : 'green'); ?>"><?php echo $this->translate($this->type); ?></span></td>
		</tr>
		<tr>
			<td><label><?php echo $this->translate('Parameters'); ?></label></td>
			<td style="text-align: left;"><?php Zend_Debug::dump($this->parameters);?></td>
		</tr>
		<tr>
			<td><label><?php echo $this->translate('Response'); ?></label></td>
			<td style="text-align: left;"><?php Zend_Debug::dump($this->response);?></td>
		</tr>
	</table>

</section>
