<header>
    <h2><?php echo $this->translate('Edit blogger'); ?></h2>
</header>

<section>

    <form name="updateBloggerForm" id="updateBloggerForm" method="post" action="">
        <dl>
            <dt width="200"><label class="label" for="name"><?php echo $this->translate('Name'); ?></label></dt>
            <dd width="*"><input type="text" class="small" id="name" name="name" value="<?php echo $this->defaults['name']; ?>" /></dd>
        </dl>
        <dl>
            <dt><label class="label" for="photo"><?php echo $this->translate('Photo'); ?></label></dt>
            <dd>
                <input type="text" class="small" id="photo" name="photo" value="<?php echo $this->defaults['photo']; ?>" />
                <a class="button" href="javascript:mcImageManager.open('updateBloggerForm','photo','','',{path : '../../../../../upload/bloggers', remember_last_path : true});"><?php echo $this->translate('Select image'); ?></a>
            </dd>
        </dl>
        <dl>
            <dt><label class="label" for="status"><?php echo $this->translate('Status'); ?></label></dt>
            <dd>
                <?php
                if(! empty($this->states) && is_array($this->states)) {
                    echo '<select name="status" id="status">';
                    foreach($this->states as $intStatusCode => $strStatus) {
                        echo '<option value="'.$intStatusCode.'"'.(($this->defaults['status'] == $intStatusCode) ? ' selected="selected"' : '').'>'.$this->translate($strStatus).'</option>';
                    }
                    echo '</select>';
                }
                ?>
        </dl>
        <dl>
            <dt>&nbsp;</dt>
            <dd><input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Update blogger'); ?>" /></dd>
        </dl>

    </form>

</section>