<header>
    <h2><?php echo $this->translate('Delete blogger'); ?></h2>
</header>

<section>

    <form name="deleteBloggerForm" method="post" action="">
        <dl>
            <dt width="200"><label class="label"><?php echo $this->translate('Name'); ?></label></dt>
            <dd width="*" class="text"><p><?php echo $this->defaults['name']; ?></p></dd>
        </dl>
        <dl>
            <dt><label class="label"><?php echo $this->translate('Status'); ?></label></dt>
            <dd class="text"><span style="margin:0;" class="tag <?php echo (($this->defaults['status'] == KZ_Controller_Action::STATE_ACTIVE) ? 'green' : 'red'); ?>"><?php echo (($this->defaults['status'] == KZ_Controller_Action::STATE_ACTIVE) ? 'active' : 'inactive'); ?></span></dd>
        </dl>
        <dl>
            <dt height="15" colspan="2"></dt>
        </dl>
        <dl>
            <dt>&nbsp;</dt>
            <dd class="text">&raquo; <?php echo $this->translate('Are you sure you want to delete this blogger and all associative blog items'); ?>?</dd>
        </dl>
        <dl>
            <dt height="15" colspan="2"></dt>
        </dl>
        <dl>
            <dt>&nbsp;</dt>
            <dd><input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Delete blogger'); ?>" /></dd>
        </dl>

    </form>

</section>