<header>
    <h2><?php echo $this->translate('Reactions'); ?></h2>
</header>

<section>

    <table class="ajax_datatable">
        <thead>
        <tr>
            <th width="50"><?php echo $this->translate('ID'); ?></th>
            <th width="*"><?php echo $this->translate('Reaction'); ?></th>
            <th width="150"><?php echo $this->translate('Profile'); ?></th>
            <th width="100"><?php echo $this->translate('Status'); ?></th>
            <th width="150"><?php echo $this->translate('Created'); ?></th>
            <th width="125"><?php echo $this->translate('Options'); ?></th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

</section>

<script type="text/javascript">
    <?php if (isset($this->editorInit)) print $this->editorInit; ?>

    jQuery(document).ready(function(){
        jQuery.fn.dataTableExt.oApi.fnFilterOnReturn = function (oSettings) {
            var _that = this;

            this.each(function (i) {
                $.fn.dataTableExt.iApiIndex = i;
                var $this = this;
                var anControl = $('input', _that.fnSettings().aanFeatures.f);
                anControl.unbind('keyup').bind('keypress', function (e) {
                    if (e.which == 13) {
                        $.fn.dataTableExt.iApiIndex = i;
                        _that.fnFilter(anControl.val());
                    }
                });
                return this;
            });
            return this;
        };

        jQuery('.ajax_datatable').dataTable( {
            "bProcessing"		: true,
            "bServerSide"		: true,
            "bStateSave"		: true,
            'iDisplayLength'	: 25,
            'sPaginationType'	: "full_numbers",
            "sAjaxSource"		: "/admin/blog/generatereactionsdatatable/",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax( {
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            },
            "aoColumns": [
                null,
                null,
                null,
                null,
                null,
                {"bSortable" : false, "bSearchable": false}
            ],
            'aaSorting'			: [[ 4, "desc" ]]
        }).fnFilterOnReturn();
    });
</script>