<script type="text/javascript">
	jQuery(document).ready(function(){

		jQuery('ul.sortable li input').each(function(){
			if(jQuery(this).attr('checked') == 'checked') {
				jQuery(this).parent().parent().css('background', '#c8e8c0');
			} else {
				jQuery(this).parent().parent().css('background', '#e8c0c0');
			}
		});

		jQuery('input.widget').change(function(){
			jQuery('ul.sortable li input').each(function(){
				if(jQuery(this).attr('checked') == 'checked') {
					jQuery(this).parent().parent().css('background', '#c8e8c0');
				} else {
					jQuery(this).parent().parent().css('background', '#e8c0c0');
				}
			});
		});

		

	});
</script>
<header>
	<h2><?php echo $this->translate('Delete widget layout'); ?></h2>
</header>
<section>
	<form name="deleteWidgetLayoutForm" method="post" action="">
		<dl>
			<dt><label class="label"><?php echo $this->translate('Name'); ?></label></dt>
			<dd class="text"><p><?php echo $this->name; ?></p></dd>
		</dl>
		<dl>
			<dt><label><?php echo $this->translate('Widgets');?></label></dt>
			<dd class="text">
				<ul>
					<?php
						foreach($this->widgets as $arrWidget) {
							
							$strBackgroundColor = ((in_array($arrWidget['widget_id'], $this->selectedWidgets)) ? '#c8e8c0;' : '#e8c0c0;');
							
							echo '<li>
									<table style="width: 310px;">
										<tr>
											<td width="*" style="background-color: '.$strBackgroundColor.'">
												<strong>'.$arrWidget['name'].'</strong>
											</td>
										</tr>
									</table>
								 </li>';
						}
					?>
				</ul>
			</dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Status'); ?></label></dt>
			<dd class="text"><p><?php echo $this->translate((($this->status == 1) ? 'Active' : 'Inactive')); ?></p></dd>
		</dl>
		
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd class="text">&raquo; <?php echo $this->translate('Are you sure you want to delete this widget layout'); ?>?</dd>
		</dl>
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Yes'); ?>" />
				<a href="/admin/widgets/layout/" title="<?php echo $this->translate('No, go back to overview'); ?>"><?php echo $this->translate('No, go back to overview'); ?></a>
			</dd>
		</dl>

	</form>
</section>