<header>
	<h2><?php echo $this->translate('Delete team member'); ?></h2>
</header>
<section>

	<form name="deleteTeamMemberForm" method="post" action="">

		<dl>
			<dt><label class="label"><?php echo $this->translate('Role'); ?></label></dt>
			<dd class="text"><?php echo ucfirst($this->translate($this->defaults['role'])); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Gender'); ?></label></dt>
			<dd class="text"><?php echo $this->translate((($this->defaults['gender'] == 'm') ? 'Male' : 'Female')); ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Firstname'); ?></label></dt>
			<dd class="text"><?php echo $this->defaults['firstname']; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Lastname'); ?></label></dt>
			<dd class="text"><?php echo $this->defaults['lastname']; ?></dd>
		</dl>
		<dl>
			<dt><label class="label"><?php echo $this->translate('Link'); ?></label></dt>
			<dd class="text"><?php echo $this->defaults['link']; ?></dd>
		</dl>

		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd class="text">&raquo; <?php echo $this->translate('Are you sure you want to delete this member'); ?>?</dd>
		</dl>
		<dl>
			<dt height="15" colspan="2"></dt>
		</dl>
		<dl>
			<dt>&nbsp;</dt>
			<dd>
				<input class="button blue" type="submit" name="formAction" value="<?php echo $this->translate('Yes'); ?>" />
				<a href="/admin/club/teamsmembers/id/<?php echo $this->defaults['team_id']; ?>" title="<?php echo $this->translate('No, go back to overview'); ?>"><?php echo $this->translate('No, go back to overview'); ?></a>
			</dd>
		</dl>

	</form>

</section>