<header>
	<h2><?php echo $this->translate('Teams'); ?></h2>
</header>
<section>
		<table class="default">
			<thead>
				<tr>
					<th width="50"><?php echo $this->translate('ID'); ?></th>
					<th width="*"><?php echo $this->translate('Name'); ?></th>
					<th width="100"><?php echo $this->translate('Category'); ?></th>
					<th width="100"><?php echo $this->translate('Sport'); ?></th>
					<th width="100"><?php echo $this->translate('Season'); ?></th>
					<th width="125"><?php echo $this->translate('Options'); ?></th>
				</tr>
			</thead>
			<tbody>

            <?php
                if(! empty($this->teams) && is_array($this->teams)) {
                    foreach($this->teams as $arrTeam) {

                        echo '<ul class="js-connected" style="float:left; width: 15%; border: 1px solid lightgrey;">';
                        echo '    <li class="title js-unsortable">KZ/Hiltex '.$arrTeam['name'].' '.$arrTeam['sport'].'</li>';
                        echo '</ul>';

                    }
                }
            ?>

			</tbody>
		</table>
		
</section>