<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.button_guestbook_leavemessage').click(function() {
            jQuery('.guestbookMessageForm').submit();
        });
    });
</script>
<div id="nextpage" class="zapp">
    <div class="col full">
        <div class="inner">

            <div class="table infobox">
                <ul class="row">
                    <li class="cell large bg_kz_blue color_kz_white guestbook">
                        <h3 class="color_kz_white left">Gastenboek - Plaats bericht</h3>
                        <?php if ($this->showsucces === true) { ?>
                            <span class="color_kz_white"><strong>Bedankt voor uw bijdrage.</strong><br>Uw bericht is in het gastenboek geplaatst.<br><br><a href="/gastenboek/" title="Keer terug naar het gastenboek" class="color_kz_yellow">&laquo; Keer terug naar het gastenboek</a></span>
                        <?php } else { ?>
                            <form name="guestbookMessageForm" class="guestbookMessageForm ketchup form-standard" method="post" action="">

                                <?php
                                if ($this->showerror != '') {
                                    echo '<span class="error">'.$this->showerror.'</span>';
                                }
                                ?>

                                <ol class="guestbook_form block-list">
                                    <li>
                                        <label for="guestbook_name">*Uw naam:</label>
                                        <input type="text" name="guestbook_name" id="guestbook_name" value="<?php echo $this->guestbook_name; ?>" data-validate="validate(required)"/>
                                    </li>
                                    <li>
                                        <label for="guestbook_email">*Uw e-mailadres:</label>
                                        <input type="text" name="guestbook_email" id="guestbook_email" value="<?php echo $this->guestbook_email; ?>" data-validate="validate(required,email)"/>
                                    </li>
                                    <li>
                                        <label for="guestbook_message">*Uw bericht:</label>
                                        <textarea type="text" name="guestbook_message" id="guestbook_message" cols="45" rows="10" data-validate="validate(required)"><?php echo $this->guestbook_message; ?></textarea>
                                    </li>
                                    <li class="captcha">
                                        <label for="captcha">*Verificatie:</label>
                                        <div class="g-recaptcha" data-sitekey="<?php echo $this->google_recaptcha_sitekey; ?>"></div>
                                    </li>
                                    <li>
                                        <a class="button_guestbook_leavemessage">Plaats mijn bericht</a>
                                    </li>
                                </ol>

                            </form>
                        <?php } ?>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</div>