<div id="nextpage" class="zapp">
	<div class="col full">
		<div class="inner">
		
			<div class="table infobox">
				<ul class="row">
					<li class="cell large bg_kz_blue color_kz_white schedule zapp">
						<h3 class="color_kz_white left">Gastenboek</h3>
						<a class="button_guestbook_leavemessage" href="/gastenboek/bericht/">Plaats bericht</a>
						<?php echo $this->guestbook(); ?>
						<a class="button_guestbook_leavemessage" href="/gastenboek/bericht/">Plaats bericht</a>
					</li>
				</ul>
			</div>

		</div>
	</div>
</div>