<div id="nextpage" class="zapp">
	<div class="col left">
		<div class="inner">
			<?php
			
				if(isset($this->content) && is_array($this->content) && count($this->content) > 0) :
				
					foreach($this->content as $intContentKey => $arrContent) :
					
						echo $this->partial($arrContent['template'], array('content' => $arrContent, 'agenda' => $this->agenda));
					
					endforeach;
				
				endif;
			
			?>
			
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_facebook_like" fb:like:width="250" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_pinterest_pinit"></a>
				<a class="addthis_counter addthis_pill_style"></a>
			</div>
			<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f8533f51464eba2"></script>
			<!-- AddThis Button END -->

		</div>
	</div>
	<div class="col right">
		<div class="item news bg_kz_lightyellow">
			<?php
			
				if(isset($this->latest) && ! empty($this->latest)) :
					
					echo '<h2>'.$this->translate('Agenda').'</h2><ol>';
					
					foreach($this->latest as $arrLatest) :
					
							if($arrLatest['agenda_id'] != $this->agenda['agenda_id']) {
								echo '	<li>
											<span class="date newstag"><a href="'.ROOT_URL.'/agenda/'.$arrLatest['nameSlug'].'" title="'.stripslashes($arrLatest['name']).'">'.$this->date()->format($arrLatest['date_start'], 'dd-MM-yyyy').(($arrLatest['date_end'] != $arrLatest['date_start']) ? ' / '.$this->date()->format($arrLatest['date_end'], 'dd-MM-yyyy') : '').'</a></span>
											<a href="'.ROOT_URL.'/agenda/'.$arrLatest['nameSlug'].'" title="'.stripslashes($arrLatest['name']).'">'.stripslashes($arrLatest['name']).'</a>
										</li>';
								
							}

					endforeach;
					
					echo '</ol>';
					
				endif;
			
			?>
		</div>
	</div>
</div>
