<div id="nextpage" class="zapp">
    <div class="col <?php echo ((! empty($this->page['fullpage']) && $this->page['fullpage'] == KZ_Controller_Action::STATE_ACTIVE) ? 'full' : 'left'); ?>">
		<div class="inner">
		
			<?php
			
				if(isset($this->content) && is_array($this->content) && count($this->content) > 0) :
				
					foreach($this->content as $intContentKey => $arrContent) :
						
						echo $this->partial($arrContent['template'], array('content' => $arrContent));
					
					endforeach;
				
				endif;
			
			?>
			
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_facebook_like" fb:like:width="110" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_counter addthis_pill_style"></a>
			</div>
			<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f8533f51464eba2"></script>
			<!-- AddThis Button END -->

		</div>
	</div>

    <?php  if(! empty($this->page['fullpage']) && $this->page['fullpage'] != KZ_Controller_Action::STATE_ACTIVE) { ?>

	<div class="col right">
		<div class="item news bg_kz_lightgrey">
			<?php
			
				if(isset($this->related) && ! empty($this->related)) :
					
					echo '<h2>'.$this->translate('Gerelateerd nieuws').'</h2><ol>';
					
					foreach($this->related as $arrRelated) :
					
							echo '	<li>
										<span class="bullet" title="'.stripslashes($arrRelated['category']).'" style="background: '.$arrRelated['category_color'].';"></span>
										<span class="date newstag"><a href="'.ROOT_URL.'/nieuws/'.$arrRelated['nameSlug'].'" title="'.stripslashes($arrRelated['name']).'">'.$this->date()->format($arrRelated['date'], 'dd MMM yyyy').'</a></span>
										<a href="'.ROOT_URL.'/nieuws/'.$arrRelated['nameSlug'].'" title="'.stripslashes($arrRelated['name']).'">'.stripslashes($arrRelated['name']).'</a>
									</li>';

					endforeach;
					
					echo '</ol>';
					
				endif;
			
			?>
		</div>
		<div class="item news bg_kz_lightgrey">
			<?php
			
				if(isset($this->latest) && ! empty($this->latest)) :
					
					echo '<h2>'.$this->translate('Laatste nieuws').'</h2><ol>';
					
					foreach($this->latest as $arrLatest) :
					
							echo '	<li>
										<span class="bullet" title="'.stripslashes($arrLatest['category']).'" style="background: '.$arrLatest['category_color'].';"></span>
										<span class="date newstag"><a href="'.ROOT_URL.'/nieuws/'.KZ_Controller_Action_Helper_Slug::slug(stripslashes($arrLatest['name'])).'" title="'.stripslashes($arrLatest['name']).'">'.$this->date()->format($arrLatest['date'], 'dd MMM yyyy').'</a></span>
										<a href="'.ROOT_URL.'/nieuws/'.KZ_Controller_Action_Helper_Slug::slug(stripslashes($arrLatest['name'])).'" title="'.stripslashes($arrLatest['name']).'">'.stripslashes($arrLatest['name']).'</a>
									</li>';

					endforeach;
					
					echo '</ol>';
					
				endif;
			
			?>
		</div>
	</div>
</div>
<?php } ?>