<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="DC.language" content="en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="Author" content="Mediaconcepts.nl">
    <?php echo $this->headMeta(); ?>
    <title><?php echo $this->seo_title; ?></title>
    <meta name="Description" content="<?php echo $this->seo_description; ?>">
    <meta name="Keywords" content="<?php echo $this->seo_keywords; ?>">

    <link rel="apple-touch-icon" sizes="180x180" href="/assets/default/image/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/default/image/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/default/image/favicon/favicon-16x16.png">
    <link rel="manifest" href="/assets/default/image/favicon/manifest.json">
    <link rel="mask-icon" href="/assets/default/image/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <link href="/assets/default/css/app.min.css" rel="stylesheet" type="text/css">
    <script src="/assets/default/script/app.sync-min.js"></script>
</head>
<body id="mobile">
<div id="full-container">
    <?php echo $this->profiles(); ?>
    <div class="menu-container">
        <?php echo $this->navigator(1); ?>
    </div>
    <div class="content-container">
        <header class="zapp">
            <div class="portrait">
                <div class="menu_button_container">
						<span class="menu_button">menu
							<span class="downarrow"><span aria-hidden="true">&#xe000;</span></span>
						</span>
                </div>
                <a href="/"><img class="logo" src="/assets/default/image/logo_kzthermo4u_portrait.png"
                                 alt="Logo kz/thermo4u"></a>
            </div>
            <?php echo $this->profiles('button'); ?>
        </header>
        <div id="wrapper_main" class="zapp">
            <div class="col main left">
                <div class="wrapper_inner">

                    <!--<a class="header--eindsprong" href="http://www.eindsprong.nl" title="Website Eindsprong" target="_blank">
                        <img src="/assets/default/image/header_website_mobile.jpg" alt="Banner eindsprong" title="Klik hier om naar de speciale website te gaan" />
                    </a>-->

                    <?php echo $this->layout()->content; ?>
                    <?php echo $this->news(true); ?>
                    <?php echo $this->widgets(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->googleanalytics; ?>
<script src="/assets/default/script/app.mobile.async-min.js"></script>
</body>
</html>