<!DOCTYPE html>

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="DC.language" content="en">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta name="Author" content="Mediaconcepts.nl">
	<?php echo $this->headMeta(); ?>
	<title><?php echo $this->seo_title; ?></title>
	<meta name="Description" content="<?php echo $this->seo_description; ?>">
	<meta name="Keywords" content="<?php echo $this->seo_keywords; ?>">
	<link href="/assets/default/css/style.less" rel="stylesheet/less" type="text/css">
	<link href="/assets/default/css/mobile.less" rel="stylesheet/less" type="text/css">
	<link href="/assets/default/css/jquery.offcanvas.less" rel="stylesheet/less" type="text/css">
	<!--[if lt IE 8]>
		<link href="/assets/default/css/table_test.less" rel="stylesheet/less" type="text/css">
	<![endif]-->
	<link href="/assets/default/css/jquery.dropdown.css" rel="stylesheet" type="text/css">
	<link href="/assets/default/css/jquery.ketchup.css" rel="stylesheet" type="text/css">
	<link href="/assets/default/css/jquery.ui.css" rel="stylesheet" type="text/css">
	<link href="/assets/default/css/jquery.flexslider.css" rel="stylesheet" type="text/css">
	<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>-->
	<script type="text/javascript" src="/assets/default/script/jquery.min.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.ui.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.easing.js"></script>
	<script type="text/javascript" src="/assets/default/script/less.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.tweet.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.flexslider-min.js"></script>
	<script type="text/javascript" src="/assets/default/script/modernizr.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.dropdown.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.ketchup.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.ketchup.validations.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.ketchup.helpers.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.responsive.js"></script>
	<script type="text/javascript" src="/assets/default/script/jquery.offcanvas.js"></script>
	<script type="text/javascript">
		
		jQuery(document).ready(function() {

			// Form Validation by Ketchup
			jQuery('.ketchup').ketchup();				
			
			//INIT TWEETS
			jQuery(function(){
				if(jQuery(".tweet").length > 0) {
					jQuery(".tweet").each(function(){
						jQuery(this).tweet({
							join_text: "auto",
							username: jQuery(this).attr('rel'),
							/*avatar_size: 60,*/
							count: 6,
							auto_join_text_default: "plaatste <a href=\"http://www.twitter.com/"+ jQuery(this).attr('rel') +"\" target=\"_blank\">@"+ jQuery(this).attr('rel') +"</a>,",
							auto_join_text_ed: jQuery(this).attr('rel'),
							auto_join_text_ing: jQuery(this).attr('rel') + " was",
							auto_join_text_reply: jQuery(this).attr('rel') + " antwoordde",
							auto_join_text_url: "plaatste <a href=\"http://www.twitter.com/"+ jQuery(this).attr('rel') +"\" target=\"_blank\">@"+ jQuery(this).attr('rel') +"</a>,",
							loading_text: "Tweets laden..."
						  });
					});
				}
			});

			/*// Paginator Width
			var paginatorWidth 	= 0;
			var margin			= 13;
			jQuery('.paginator li').each(function(){
				paginatorWidth		= paginatorWidth + (((parseInt(jQuery(this).css('width')) + margin)) / 2);
			});
			jQuery('.paginator').css('width', paginatorWidth);*/

			// Change Results Text
			if(jQuery('.clubplugin.standings').length > 0) {
				jQuery('.clubplugin.standings .gespeeld').html('G');
				jQuery('.clubplugin.standings .punten').html('P');
				jQuery('.clubplugin.standings .winst').html('W');
				jQuery('.clubplugin.standings .verlies').html('V');
				jQuery('.clubplugin.standings .gelijk').html('G');
				jQuery('.clubplugin.standings .voor').html('V');
				jQuery('.clubplugin.standings .tegen').html('T');
				jQuery('.clubplugin.standings .saldo').html('S');
				jQuery('.clubplugin.standings .mindering').html('M');
			}

			// Set Youtube Widget Slider
			jQuery('#widget-slider').flexslider({
				minItems: 1,
				maxItems: 2,
				itemWidth: 105,
				itemMargin:0,
				animation: 'slide',
				animationSpeed: 1500,
				startAt: 0,
				directionNav: false,
				controlNav: true,
				pauseOnHover: true,
			});

			// Get Match Program Info
			jQuery('ol.clubplugin.program li.widget').click(function(){

				jQuery('ol.clubplugin.program li.widget').removeClass('active');
				jQuery('ul.row li.schedule div#match_info_program').html('');
				jQuery('ul.row li.schedule #match_info_program').css('display', 'none');
				
				jQuery(this).addClass('active');
				jQuery('#match_info_program').html('');
				
				var position 		= jQuery(this).position();
				var elementHeight 	= jQuery(this).outerHeight();
				var elementWidth 	= jQuery(this).outerWidth();
				var elementMatchID 	= jQuery(this).attr('rel');

				jQuery('#match_info_program').css('display', 'block');
				jQuery('#match_info_program').css('top', Math.floor(position.top) + elementHeight);
				jQuery('#match_info_program').css('left', Math.round(position.left));
				jQuery('#match_info_program').css('width', elementWidth);

				jQuery.get("/tools/teaminfo", {match_id:elementMatchID}).done(function(data) {
					jQuery('#match_info_program').html(data);
				});

			});

			jQuery("div#match_info_program").live({
				click: function() {
					jQuery('ol.clubplugin.program li.widget').removeClass('active');
					jQuery('ul.row li.schedule div#match_info_program').html('');
					jQuery('ul.row li.schedule #match_info_program').css('display', 'none');
				}
			});

			// Get Match Results Info
			jQuery('ol.clubplugin.results li.widget').click(function(){

				jQuery('ol.clubplugin.results li.widget').removeClass('active');
				jQuery('ul.row li.results div#match_info_results').html('');
				jQuery('ul.row li.results #match_info_results').css('display', 'none');
				
				jQuery(this).addClass('active');
				jQuery('#match_info_results').html('');
				
				var position 		= jQuery(this).position();
				var elementHeight 	= jQuery(this).outerHeight();
				var elementWidth 	= jQuery(this).outerWidth();
				var elementMatchID 	= jQuery(this).attr('rel');

				jQuery('#match_info_results').css('display', 'block');
				jQuery('#match_info_results').css('top', Math.floor(position.top) + elementHeight);
				jQuery('#match_info_results').css('left', Math.round(position.left));
				jQuery('#match_info_results').css('width', elementWidth);

				jQuery.get("/tools/teaminfo", {match_id:elementMatchID}).done(function(data) {
					jQuery('#match_info_results').html(data);
				});

			});

			jQuery("div#match_info_results").live({
				click: function() {
					jQuery('ol.clubplugin.results li.widget').removeClass('active');
					jQuery('ul.row li.results div#match_info_results').html('');
					jQuery('ul.row li.results #match_info_results').css('display', 'none');
				}
			});

			// Set News Dropdown on Full Width
			jQuery('.dropdown_button').click(function(){
				// Set Dropdown width Addition
				var dropdown_width_addition = 34;
				var dropdown_width			= jQuery(this).width() + dropdown_width_addition;
				jQuery('#newsDropdown ul').css('width', dropdown_width + 'px');
				jQuery('#newsDropdown ul').css('max-width', dropdown_width + 'px');
				jQuery('#newsDropdown ul').css('min-width', dropdown_width + 'px');
			});

//			// Login Profiles
//			jQuery('.openProfiles').click(function(){
//				jQuery('.l-wrapper--profiles').show();
//				jQuery(this).hide();
//			});

			// SIDEBAR OFFCANVAS
			jQuery().offcanvas();
			
		});

		/*function portraitMenuButton() {
			if(jQuery('nav').css('display') == 'none') {
				jQuery('.menu_button').css('cssText', 'border-bottom-right-radius: 0 !important; -moz-border-radius-bottomright: 0 !important; -webkit-border-bottom-right-radius: 0 !important; border-bottom-left-radius: 0 !important; -moz-border-radius-bottomleft: 0 !important; -webkit-border-bottom-left-radius: 0 !important;');
				jQuery('nav').css('cssText', 'display: block !important;');
			} else {
				jQuery('.menu_button').css('cssText', 'border-bottom-right-radius: 5px !important; -moz-border-radius-bottomright: 5px !important; -webkit-border-bottom-right-radius: 5px !important; border-bottom-left-radius: 5px !important; -moz-border-radius-bottomleft: 5px !important; -webkit-border-bottom-left-radius: 5px !important;');
				jQuery('nav').css('cssText', 'display: none !important');
			}
		}*/
	

	</script>
</head>
<body id="mobile">
	<div id="full-container">
		<?php //echo $this->profiles(); ?>
		<div class="menu-container">
			<?php echo $this->navigator(1); ?>
		</div>
		<div class="content-container">
			<header class="zapp">
				<div class="portrait">
					<div class="menu_button_container">
						<span class="menu_button">menu
							<span class="downarrow"><span aria-hidden="true">&#xe000;</span></span>
						</span>
					</div>
					<a href="/"><img class="logo" src="/assets/default/image/logo_kzhiltex_portrait.png" alt="Logo kz/hiltex"></a>
				</div>
				<?php //echo $this->profiles('button'); ?>
			</header>
			<div id="wrapper_main" class="zapp">
				<div class="col main left">
					<div class="wrapper_inner">

						<!--<a class="header--eindsprong" href="http://www.eindsprong.nl" title="Website Eindsprong" target="_blank">
							<img src="/assets/default/image/header_website_mobile.jpg" alt="Banner eindsprong" title="Klik hier om naar de speciale website te gaan" />
						</a>-->

						<?php echo $this->layout()->content; ?>
						<?php echo $this->news(true); ?>
						<?php echo $this->widgets(); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php echo $this->googleanalytics; ?>
</body>
</html>